<?php

use Illuminate\Database\Seeder;

class CaoFaturaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cao_fatura')->delete();
        
        \DB::table('cao_fatura')->insert(array (
            0 => 
            array (
                'co_fatura' => 1,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 433,
                'total' => 7160.35986328125,
                'valor' => 6720,
                'data_emissao' => '2007-01-25',
                'corpo_nf' => 'Parcela mensal referente à prestação de serviço de consultoria em processos e integração de sistemas. conforme OS-SF-029',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            1 => 
            array (
                'co_fatura' => 2,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 436,
                'total' => 10560.5,
                'valor' => 9911,
                'data_emissao' => '2007-02-01',
                'corpo_nf' => 'Referente a 187 horas do mês de janeiro/2007 de alocação de
recurso java para o desenvolvimento de sistemas para a área de Vendas.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            2 => 
            array (
                'co_fatura' => 3,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 437,
                'total' => 10334.599609375,
                'valor' => 9699,
                'data_emissao' => '2007-02-01',
                'corpo_nf' => 'Referente a 183 horas do mês de janeiro/2007 de alocação do
recurso Francisco Ogatha em análise/desenvolvimento de sistemas java.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            3 => 
            array (
                'co_fatura' => 4,
                'co_cliente' => 46,
                'co_sistema' => 113,
                'co_os' => 1013,
                'num_nf' => 0,
                'total' => 816,
                'valor' => 803.760009765625,
                'data_emissao' => '2007-02-05',
                'corpo_nf' => 'Orbe Investimentos - OS008 – Upgrade – Versão para Investidores Estrangeiros',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            4 => 
            array (
                'co_fatura' => 5,
                'co_cliente' => 7028,
                'co_sistema' => 240,
                'co_os' => 994,
                'num_nf' => 432,
                'total' => 7366.64990234375,
                'valor' => 6913.60009765625,
                'data_emissao' => '2007-01-19',
                'corpo_nf' => 'parcela 1 de 05 referente OS 01 q contempla o desenvolvimento e implantação do sistema SAAP ',
                'comissao_cn' => 12,
                'total_imp_inc' => 16,
            ),
            5 => 
            array (
                'co_fatura' => 6,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 420,
                'total' => 8613.75,
                'valor' => 8084,
                'data_emissao' => '2007-01-02',
                'corpo_nf' => 'Referente a 188 horas do mês de dezembro/2006 de alocação de
recurso java para o desenvolvimento de sistemas para a área de Vendas.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            6 => 
            array (
                'co_fatura' => 7,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 421,
                'total' => 8842.830078125,
                'valor' => 8299,
                'data_emissao' => '2007-01-02',
                'corpo_nf' => 'Referente a 193 horas do mês de dezembro/2006 de alocação do
recurso Francisco Ogatha em análise/desenvolvimento de sistemas java.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            7 => 
            array (
                'co_fatura' => 8,
                'co_cliente' => 3,
                'co_sistema' => 152,
                'co_os' => 979,
                'num_nf' => 435,
                'total' => 2972.830078125,
                'valor' => 2790,
                'data_emissao' => '2007-01-31',
                'corpo_nf' => 'Referente a 45 horas do mês de janeiro/2007 de treinamento.
acompanhamento. consultoria e Adequações do sistema. In loco.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            8 => 
            array (
                'co_fatura' => 9,
                'co_cliente' => 7007,
                'co_sistema' => 207,
                'co_os' => 735,
                'num_nf' => 438,
                'total' => 2850.760009765625,
                'valor' => 2808,
                'data_emissao' => '2007-02-07',
                'corpo_nf' => 'Parcela 3 de 4 referente a OS 001 do desenvolvimento e implantação do Okube Sales e Chamados',
                'comissao_cn' => 10,
                'total_imp_inc' => 21,
            ),
            9 => 
            array (
                'co_fatura' => 10,
                'co_cliente' => 7031,
                'co_sistema' => 247,
                'co_os' => 1028,
                'num_nf' => 446,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-02-14',
                'corpo_nf' => 'manutencao siscon dj',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            10 => 
            array (
                'co_fatura' => 11,
                'co_cliente' => 2,
                'co_sistema' => 149,
                'co_os' => 425,
                'num_nf' => 445,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-02-14',
                'corpo_nf' => 'manutencao siscon dj',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            11 => 
            array (
                'co_fatura' => 12,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 449,
                'total' => 8132.1298828125,
                'valor' => 7632,
                'data_emissao' => '2007-03-05',
                'corpo_nf' => 'Referente a 144 horas do mês de janeiro/2007 de alocação de recurso java para o desenvolvimento de sistemas para a área de Vendas',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            12 => 
            array (
                'co_fatura' => 13,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 450,
                'total' => 9826.3203125,
                'valor' => 9222,
                'data_emissao' => '2007-03-05',
                'corpo_nf' => 'Referente a 174 horas do mês de janeiro/2007 de alocação do recurso Francisco Ogatha em análise/desenvolvimento de sistemas java',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            13 => 
            array (
                'co_fatura' => 14,
                'co_cliente' => 7007,
                'co_sistema' => 207,
                'co_os' => 735,
                'num_nf' => 451,
                'total' => 2850.760009765625,
                'valor' => 2808,
                'data_emissao' => '2007-03-08',
                'corpo_nf' => 'Parcela 4 de 4 referente a OS 001 do desenvolvimento e implantação do Okube Sales e Chamados',
                'comissao_cn' => 10,
                'total_imp_inc' => 21,
            ),
            14 => 
            array (
                'co_fatura' => 15,
                'co_cliente' => 7028,
                'co_sistema' => 240,
                'co_os' => 994,
                'num_nf' => 447,
                'total' => 7366.64990234375,
                'valor' => 6913.60009765625,
                'data_emissao' => '2007-02-16',
                'corpo_nf' => 'Parcela 02 de 05. referente a OS 001 que contempla o desenvolvimento e a implantação do sistema SAPP - Sistema de Acompanhamento de Projeto Pedagógico',
                'comissao_cn' => 12,
                'total_imp_inc' => 16,
            ),
            15 => 
            array (
                'co_fatura' => 16,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 452,
                'total' => 7227.509765625,
                'valor' => 6783.02001953125,
                'data_emissao' => '2007-03-14',
            'corpo_nf' => 'Elaboração de programas (software). Conforme OS-SF-001. OS-SF-002. OS-SF-005 e OS-SF-028.',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            16 => 
            array (
                'co_fatura' => 17,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 457,
                'total' => 6142.669921875,
                'valor' => 5764.89990234375,
                'data_emissao' => '2007-03-14',
            'corpo_nf' => 'Elaboração de programas (software). Conforme OS-SF-001. OS-SF-002. OS-SF-005 e OS-SF-028 e SF-1024.',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            17 => 
            array (
                'co_fatura' => 18,
                'co_cliente' => 7035,
                'co_sistema' => 249,
                'co_os' => 1049,
                'num_nf' => 458,
                'total' => 3476.139892578125,
                'valor' => 3424,
                'data_emissao' => '2007-03-14',
                'corpo_nf' => 'Parcela 01 de 02. referente a OS 001 que contempla o desenvolvimento e a implantação do sistema SPO - Sistema de Pedidos OnLine',
                'comissao_cn' => 15,
                'total_imp_inc' => 16,
            ),
            18 => 
            array (
                'co_fatura' => 20,
                'co_cliente' => 2,
                'co_sistema' => 149,
                'co_os' => 425,
                'num_nf' => 460,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-03-15',
                'corpo_nf' => 'Parcela referente a manutenção do mês de fevereiro/2007 das funcionalidades
existentes no SisconDJ instalado no TJMT',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            19 => 
            array (
                'co_fatura' => 21,
                'co_cliente' => 7031,
                'co_sistema' => 247,
                'co_os' => 1028,
                'num_nf' => 461,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-03-15',
                'corpo_nf' => 'Parcela referente a manutenção do mês de fevereiro/2007 das funcionalidades existentes no SisconDJ instalado no TJAM
',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            20 => 
            array (
                'co_fatura' => 22,
                'co_cliente' => 6941,
                'co_sistema' => 219,
                'co_os' => 882,
                'num_nf' => 462,
                'total' => 2800,
                'valor' => 2758,
                'data_emissao' => '2007-03-15',
                'corpo_nf' => 'Referente ao mês de dezembro/2006 do recurso Marco Malaquias. código:4500212031. do projeto Outsourcing VIVO',
                'comissao_cn' => 0,
                'total_imp_inc' => 21,
            ),
            21 => 
            array (
                'co_fatura' => 23,
                'co_cliente' => 6941,
                'co_sistema' => 219,
                'co_os' => 882,
                'num_nf' => 463,
                'total' => 2940,
                'valor' => 2628.989990234375,
                'data_emissao' => '2007-03-15',
                'corpo_nf' => 'Referente ao mês de janeiro/2007 do recurso Marco Malaquias. código:4500212031. do projeto Outsourcing VIVO',
                'comissao_cn' => 0,
                'total_imp_inc' => 21,
            ),
            22 => 
            array (
                'co_fatura' => 24,
                'co_cliente' => 3,
                'co_sistema' => 166,
                'co_os' => 1055,
                'num_nf' => 465,
                'total' => 5600,
                'valor' => 5255.60009765625,
                'data_emissao' => '2007-03-15',
                'corpo_nf' => 'Parcela 1 de 4 referente a OS 001 de desenvolvimento de upgrade
no sistema. contemplando novas funcionalidades. novos relatórios e ajustes
em relatórios existentes.
',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            23 => 
            array (
                'co_fatura' => 25,
                'co_cliente' => 46,
                'co_sistema' => 113,
                'co_os' => 1063,
                'num_nf' => 0,
                'total' => 652.79998779296875,
                'valor' => 652.79998779296875,
                'data_emissao' => '2007-03-21',
                'corpo_nf' => 'Adaptação da estrutura das páginas listadas abaixo. de forma a permitir a perfeita leitura / navegação do seu conteúdo pelo software Mozilla Firefox.',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            24 => 
            array (
                'co_fatura' => 26,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 466,
                'total' => 7906.22998046875,
                'valor' => 7420,
                'data_emissao' => '2007-03-23',
                'corpo_nf' => 'Referente a 140 horas do mês parcial de março/2007 de alocação
do recurso Francisco Ogatha em análise/desenvolvimento de sistemas java.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            25 => 
            array (
                'co_fatura' => 27,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 467,
                'total' => 7123.06982421875,
                'valor' => 6685,
                'data_emissao' => '2007-03-23',
            'corpo_nf' => 'Referente a 125 horas do mês parcial de março de alocação de recurso java para o desenvolvimento de sistemas para a área de Vendas. Incluso também despesas de deslocamento para reunião no CENU (R$ 60.00).',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            26 => 
            array (
                'co_fatura' => 28,
                'co_cliente' => 7028,
                'co_sistema' => 240,
                'co_os' => 994,
                'num_nf' => 468,
                'total' => 7366.64990234375,
                'valor' => 6913.60009765625,
                'data_emissao' => '2007-03-27',
                'corpo_nf' => 'SAPP - Sistema de Acompanhamento de Projeto Pedagógico.',
                'comissao_cn' => 12,
                'total_imp_inc' => 16,
            ),
            27 => 
            array (
                'co_fatura' => 29,
                'co_cliente' => 7030,
                'co_sistema' => 243,
                'co_os' => 1005,
                'num_nf' => 0,
                'total' => 3146.39990234375,
                'valor' => 3146.39990234375,
                'data_emissao' => '2007-03-29',
                'corpo_nf' => 'parcela 2 do Website Departida',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            28 => 
            array (
                'co_fatura' => 30,
                'co_cliente' => 6991,
                'co_sistema' => 126,
                'co_os' => 989,
                'num_nf' => 0,
                'total' => 759.3599853515625,
                'valor' => 759.3599853515625,
                'data_emissao' => '2007-03-29',
                'corpo_nf' => 'upgrade website riscali- coluna de utilidades',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            29 => 
            array (
                'co_fatura' => 31,
                'co_cliente' => 6936,
                'co_sistema' => 246,
                'co_os' => 1027,
                'num_nf' => 470,
                'total' => 2800,
                'valor' => 2758,
                'data_emissao' => '2007-04-03',
                'corpo_nf' => 'Sistema de pesquisa e segmentação mercadológica. a ser usada pela Digital Group. junto aos seus clientes.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            30 => 
            array (
                'co_fatura' => 32,
                'co_cliente' => 7039,
                'co_sistema' => 251,
                'co_os' => 1072,
                'num_nf' => 0,
                'total' => 2000,
                'valor' => 2000,
                'data_emissao' => '2007-04-04',
                'corpo_nf' => 'concepçao de logomarca e fundo de reserva para website',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            31 => 
            array (
                'co_fatura' => 33,
                'co_cliente' => 7007,
                'co_sistema' => 207,
                'co_os' => 735,
                'num_nf' => 471,
                'total' => 2412.179931640625,
                'valor' => 2376,
                'data_emissao' => '2007-04-09',
                'corpo_nf' => 'Parcela 1 de 2 referente a OS 002 de desenvolvimento e
implantação de adequações nos módulos KChamados e KSales do sistema Okube.',
                'comissao_cn' => 10,
                'total_imp_inc' => 21,
            ),
            32 => 
            array (
                'co_fatura' => 34,
                'co_cliente' => 7026,
                'co_sistema' => 237,
                'co_os' => 987,
                'num_nf' => 472,
                'total' => 16334.599609375,
                'valor' => 15330,
                'data_emissao' => '2007-04-09',
                'corpo_nf' => 'Parcela única referente a OS de desenvolvimento e implantação do SGV Compact
(Emplacamentos) conforme OS 001',
                'comissao_cn' => 14,
                'total_imp_inc' => 16,
            ),
            33 => 
            array (
                'co_fatura' => 35,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 473,
                'total' => 7358.2998046875,
                'valor' => 6905.759765625,
                'data_emissao' => '2007-04-10',
                'corpo_nf' => 'Elaboracao de programas software. Conforme OS-SF-001. OS-SF-002. OS-SF-005. OS-SF-028 e SF-1024.',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            34 => 
            array (
                'co_fatura' => 36,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 342,
                'num_nf' => 478,
                'total' => 5488.759765625,
                'valor' => 5151.2001953125,
                'data_emissao' => '2007-04-10',
                'corpo_nf' => 'Elaboracao de programas software. Conforme OS-SF-001. OS-SF-002. OS-SF-005. OS-SF-028 e SF-1024.',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            35 => 
            array (
                'co_fatura' => 37,
                'co_cliente' => 7007,
                'co_sistema' => 207,
                'co_os' => 986,
                'num_nf' => 479,
                'total' => 2412.179931640625,
                'valor' => 2376,
                'data_emissao' => '2007-04-10',
                'corpo_nf' => 'Parcela 2 de 2 referente a OS 002 de desenvolvimento e implantação de adequações nos módulos KChamados e KSales do sistema Okube.',
                'comissao_cn' => 10,
                'total_imp_inc' => 21,
            ),
            36 => 
            array (
                'co_fatura' => 38,
                'co_cliente' => 7007,
                'co_sistema' => 207,
                'co_os' => 1036,
                'num_nf' => 480,
                'total' => 997.34002685546875,
                'valor' => 936,
                'data_emissao' => '2007-04-16',
                'corpo_nf' => 'Parcela única referente a OS 004 de desenvolvimento e implantação de adequações no módulo KChamados do sistema Okube.
',
                'comissao_cn' => 10,
                'total_imp_inc' => 21,
            ),
            37 => 
            array (
                'co_fatura' => 39,
                'co_cliente' => 2,
                'co_sistema' => 102,
                'co_os' => 676,
                'num_nf' => 481,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-04-16',
                'corpo_nf' => 'Parcela referente a manutenção do mês de março/2007 das funcionalidades
existentes no SisconDJ instalado no TJMT',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            38 => 
            array (
                'co_fatura' => 40,
                'co_cliente' => 7031,
                'co_sistema' => 247,
                'co_os' => 1028,
                'num_nf' => 481,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-04-16',
                'corpo_nf' => 'Parcela referente a manutenção do mês de março/2007 das funcionalidades
existentes no SisconDJ instalado no TJAM',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            39 => 
            array (
                'co_fatura' => 41,
                'co_cliente' => 3,
                'co_sistema' => 152,
                'co_os' => 979,
                'num_nf' => 483,
                'total' => 2203.050048828125,
                'valor' => 2170,
                'data_emissao' => '2007-04-16',
                'corpo_nf' => 'Referente a 35 horas do mês de março até 16/abril de 2007 de treinamento. acompanhamento. consultoria e Adequações do sistema. In loco',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            40 => 
            array (
                'co_fatura' => 42,
                'co_cliente' => 7022,
                'co_sistema' => 254,
                'co_os' => 1085,
                'num_nf' => 483,
                'total' => 2785.7900390625,
                'valor' => 2744,
                'data_emissao' => '2007-04-17',
                'corpo_nf' => 'Parcela 01 de 02. referente a OS 001 que contempla o desenvolvimento e a implantação do Website My Fair Lady',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
            41 => 
            array (
                'co_fatura' => 43,
                'co_cliente' => 7028,
                'co_sistema' => 240,
                'co_os' => 994,
                'num_nf' => 485,
                'total' => 7366.64990234375,
                'valor' => 6913.60009765625,
                'data_emissao' => '2007-04-23',
                'corpo_nf' => 'SAPP - Sistema de Acompanhamento de Projeto Pedagógico',
                'comissao_cn' => 12,
                'total_imp_inc' => 16,
            ),
            42 => 
            array (
                'co_fatura' => 44,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 342,
                'num_nf' => 486,
                'total' => 7160.35986328125,
                'valor' => 6720,
                'data_emissao' => '2007-04-24',
                'corpo_nf' => 'Parcela mensal referente à prestação de serviço de consultoria em processos e integração de sistemas. conforme OS-SF-029',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            43 => 
            array (
                'co_fatura' => 45,
                'co_cliente' => 3,
                'co_sistema' => 166,
                'co_os' => 1055,
                'num_nf' => 487,
                'total' => 10407,
                'valor' => 9766.9697265625,
                'data_emissao' => '2007-04-25',
                'corpo_nf' => 'Parcela 2 de 4 referente a OS 001 de desenvolvimento de upgrade no sistema. contemplando novas funcionalidades. novos relatórios e ajustes em relatórios existentes.
',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            44 => 
            array (
                'co_fatura' => 46,
                'co_cliente' => 7038,
                'co_sistema' => 256,
                'co_os' => 1094,
                'num_nf' => 488,
                'total' => 2833.330078125,
                'valor' => 2790.830078125,
                'data_emissao' => '2007-04-27',
                'corpo_nf' => 'consultoria de processos. análise de sistemas e elaboração de documentos',
                'comissao_cn' => 15,
                'total_imp_inc' => 16,
            ),
            45 => 
            array (
                'co_fatura' => 47,
                'co_cliente' => 6936,
                'co_sistema' => 253,
                'co_os' => 1082,
                'num_nf' => 489,
                'total' => 2000,
                'valor' => 1970,
                'data_emissao' => '2007-05-02',
                'corpo_nf' => 'Projeto “O Melhor Lugar do Mundo"',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            46 => 
            array (
                'co_fatura' => 48,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 490,
                'total' => 11859.2998046875,
                'valor' => 11130,
                'data_emissao' => '2007-05-02',
            'corpo_nf' => 'Referente a 210 horas do mês de março (23/3/2007. 26/3/2007. 27/3/2007. 28/3/2007. 29/3/2007 e 30/3/2007) e de abril de 2007 de alocação de recurso java para o desenvolvimento de sistemas para a área de Vendas.',
                'comissao_cn' => 9,
                'total_imp_inc' => 16,
            ),
            47 => 
            array (
                'co_fatura' => 49,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 491,
                'total' => 12028.7998046875,
                'valor' => 11289,
                'data_emissao' => '2007-05-02',
            'corpo_nf' => 'Referente a 213 horas do mês de março (23/3/2007. 26/3/2007. 27/3/2007. 28/3/2007. 29/3/2007 e 30/3/2007) e abril/2007 de alocação do recurso Francisco Ogatha em análise/desenvolvimento de sistemas java.',
                'comissao_cn' => 9,
                'total_imp_inc' => 16,
            ),
            48 => 
            array (
                'co_fatura' => 50,
                'co_cliente' => 6936,
                'co_sistema' => 246,
                'co_os' => 1027,
                'num_nf' => 492,
                'total' => 2800,
                'valor' => 2758,
                'data_emissao' => '2007-05-02',
                'corpo_nf' => 'Referente à segunda parcela do projeto Sistema Digital Pesquisa',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            49 => 
            array (
                'co_fatura' => 51,
                'co_cliente' => 2,
                'co_sistema' => 149,
                'co_os' => 1090,
                'num_nf' => 493,
                'total' => 2976,
                'valor' => 2931.360107421875,
                'data_emissao' => '2007-05-02',
                'corpo_nf' => 'Parcela única referente a OS 15 de desenvolvimento e implantação de upgrade na versão 2.0 do sisconDJ.
',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            50 => 
            array (
                'co_fatura' => 52,
                'co_cliente' => 7043,
                'co_sistema' => 258,
                'co_os' => 1102,
                'num_nf' => 494,
                'total' => 7989.33984375,
                'valor' => 7498,
                'data_emissao' => '2007-05-07',
            'corpo_nf' => 'Parcela 1 de 2 referente a OS 001 de desenvolvimento e implantação do portal colaborativo da Assurant. UFI (Universo Finance & Insurance).
',
                'comissao_cn' => 14,
                'total_imp_inc' => 16,
            ),
            51 => 
            array (
                'co_fatura' => 53,
                'co_cliente' => 7039,
                'co_sistema' => 251,
                'co_os' => 1073,
                'num_nf' => 0,
                'total' => 2000,
                'valor' => 2000,
                'data_emissao' => '2007-05-08',
                'corpo_nf' => 'segunda parcela de desenvolvimento do website search RH',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            52 => 
            array (
                'co_fatura' => 54,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 495,
                'total' => 7255.56982421875,
                'valor' => 6809.35009765625,
                'data_emissao' => '2007-05-08',
                'corpo_nf' => 'Elaboracao de programas software. Conforme OS-SF-001. OS-SF-002. OS-SF-005. OS-SF-028 e SF-1024',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            53 => 
            array (
                'co_fatura' => 55,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 500,
                'total' => 6002.39990234375,
                'valor' => 5633.25,
                'data_emissao' => '2007-05-08',
                'corpo_nf' => 'Elaboração de programas software. Conforme OS-SF-001. OS-SF-002. OS-SF-005. OS-SF-028 e SF-1024',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            54 => 
            array (
                'co_fatura' => 56,
                'co_cliente' => 7044,
                'co_sistema' => 259,
                'co_os' => 1108,
                'num_nf' => 0,
                'total' => 685.44000244140625,
                'valor' => 685.44000244140625,
                'data_emissao' => '2007-05-10',
                'corpo_nf' => 'desenvolvimento de sistema de monitoramento de BC',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            55 => 
            array (
                'co_fatura' => 57,
                'co_cliente' => 3,
                'co_sistema' => 166,
                'co_os' => 1055,
                'num_nf' => 501,
                'total' => 7991.47998046875,
                'valor' => 7500,
                'data_emissao' => '2007-05-15',
                'corpo_nf' => 'Parcela 3 de 4 referente a OS 001 de desenvolvimento de upgrade no sistema. contemplando novas funcionalidades. novos relatórios e ajustes em relatórios existentes.
',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            56 => 
            array (
                'co_fatura' => 58,
                'co_cliente' => 2,
                'co_sistema' => 149,
                'co_os' => 425,
                'num_nf' => 502,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-05-17',
                'corpo_nf' => 'Parcela referente a manutenção do mês de abril-maio/2007 das funcionalidades existentes no SisconDJ instalado no TJMT',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            57 => 
            array (
                'co_fatura' => 59,
                'co_cliente' => 7031,
                'co_sistema' => 247,
                'co_os' => 1028,
                'num_nf' => 503,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-05-17',
                'corpo_nf' => 'Parcela referente a manutenção do mês de abril-maio/2007 das funcionalidades existentes no SisconDJ instalado no TJAM
',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            58 => 
            array (
                'co_fatura' => 60,
                'co_cliente' => 7028,
                'co_sistema' => 240,
                'co_os' => 994,
                'num_nf' => 505,
                'total' => 7366.64990234375,
                'valor' => 6913.60009765625,
                'data_emissao' => '2007-05-21',
                'corpo_nf' => 'SAPP - Sistema de Acompanhamento de Projeto Pedagógico',
                'comissao_cn' => 12,
                'total_imp_inc' => 16,
            ),
            59 => 
            array (
                'co_fatura' => 61,
                'co_cliente' => 7022,
                'co_sistema' => 254,
                'co_os' => 1085,
                'num_nf' => 506,
                'total' => 2785.7900390625,
                'valor' => 2744,
                'data_emissao' => '2007-05-21',
                'corpo_nf' => 'Parcela 02 de 02. referente a OS 001 que contempla o desenvolvimento e a implantação do Website My Fair Lady',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
            60 => 
            array (
                'co_fatura' => 62,
                'co_cliente' => 7038,
                'co_sistema' => 256,
                'co_os' => 1094,
                'num_nf' => 508,
                'total' => 2833.330078125,
                'valor' => 2790.830078125,
                'data_emissao' => '2007-05-29',
                'corpo_nf' => 'Consultoria de processos. análise de sistemas e elaboração de documentos',
                'comissao_cn' => 15,
                'total_imp_inc' => 16,
            ),
            61 => 
            array (
                'co_fatura' => 63,
                'co_cliente' => 992,
                'co_sistema' => 260,
                'co_os' => 1112,
                'num_nf' => 509,
                'total' => 25577,
                'valor' => 24004,
                'data_emissao' => '2007-05-30',
                'corpo_nf' => 'Desenvolvimento e Implantação do Hotsite Sadia Club',
                'comissao_cn' => 8,
                'total_imp_inc' => 21,
            ),
            62 => 
            array (
                'co_fatura' => 64,
                'co_cliente' => 6936,
                'co_sistema' => 246,
                'co_os' => 1027,
                'num_nf' => 510,
                'total' => 2800,
                'valor' => 2758,
                'data_emissao' => '2007-06-01',
                'corpo_nf' => 'Referente à terceira parcela do projeto Sistema Digital Pesquisa',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            63 => 
            array (
                'co_fatura' => 65,
                'co_cliente' => 6936,
                'co_sistema' => 253,
                'co_os' => 1082,
                'num_nf' => 511,
                'total' => 2000,
                'valor' => 1970,
                'data_emissao' => '2007-06-01',
                'corpo_nf' => 'Projeto “O Melhor Lugar do Mundo"',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            64 => 
            array (
                'co_fatura' => 66,
                'co_cliente' => 7040,
                'co_sistema' => 252,
                'co_os' => 1079,
                'num_nf' => 512,
                'total' => 2968.02001953125,
                'valor' => 2923.5,
                'data_emissao' => '2007-06-01',
                'corpo_nf' => 'Parcela 01 de 04. referente a OS 001 que contempla o desenvolvimento e a implantação do SPO - Sistema de Pedidos Online da Compactor.',
                'comissao_cn' => 14,
                'total_imp_inc' => 16,
            ),
            65 => 
            array (
                'co_fatura' => 67,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 513,
                'total' => 10729.900390625,
                'valor' => 10070,
                'data_emissao' => '2007-06-01',
                'corpo_nf' => 'Referente a 190 horas do mês de maio/2007 de alocação do recurso Francisco Ogatha em análise/desenvolvimento de sistemas java',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            66 => 
            array (
                'co_fatura' => 68,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 514,
                'total' => 11633.5,
                'valor' => 10918,
                'data_emissao' => '2007-06-01',
                'corpo_nf' => 'Referente a 206 horas do mês de maio de 2007 de alocação de recurso java para o desenvolvimento de sistemas para a área de Vendas',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            67 => 
            array (
                'co_fatura' => 69,
                'co_cliente' => 46,
                'co_sistema' => 113,
                'co_os' => 1128,
                'num_nf' => 0,
                'total' => 488,
                'valor' => 488,
                'data_emissao' => '2007-06-11',
                'corpo_nf' => 'OS 010 - Upgrade -> Inclusão de Novo Fundo de Investimento',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            68 => 
            array (
                'co_fatura' => 70,
                'co_cliente' => 7031,
                'co_sistema' => 247,
                'co_os' => 999,
                'num_nf' => 515,
                'total' => 6425,
                'valor' => 6029.85986328125,
                'data_emissao' => '2007-06-11',
                'corpo_nf' => 'Parcela 1 de 2 referente consultoria e desenvolvimento de adequações SisconDJ 2.0 para a Lei Federal 10.819/2003.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            69 => 
            array (
                'co_fatura' => 71,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 516,
                'total' => 6249.89013671875,
                'valor' => 5865.52001953125,
                'data_emissao' => '2007-06-12',
                'corpo_nf' => 'Elaboracao de programas software. Conforme OS-SF-001. OS-SF-002. OS-SF-005 e OS-SF-028.',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            70 => 
            array (
                'co_fatura' => 73,
                'co_cliente' => 7047,
                'co_sistema' => 264,
                'co_os' => 1150,
                'num_nf' => 523,
                'total' => 2880.72998046875,
                'valor' => 2837.52001953125,
                'data_emissao' => '2007-06-14',
            'corpo_nf' => 'Parcela 01 de 05. referente a OS 001 que contempla Refactoring e Redesign do Website Chevrolet Nova e dos cinco Hotsites de frotistas mantidos pelo grupo (Citiclub. CIMEB. Central do Hoteleiro. Novartis e Unilever).',
                'comissao_cn' => 14,
                'total_imp_inc' => 21,
            ),
            71 => 
            array (
                'co_fatura' => 74,
                'co_cliente' => 2,
                'co_sistema' => 149,
                'co_os' => 425,
                'num_nf' => 524,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-06-18',
                'corpo_nf' => 'Parcela referente a manutenção do mês de maio-junho/2007 das funcionalidades existentes no SisconDJ instalado no TJMT',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            72 => 
            array (
                'co_fatura' => 75,
                'co_cliente' => 7043,
                'co_sistema' => 258,
                'co_os' => 1102,
                'num_nf' => 526,
                'total' => 7989.33984375,
                'valor' => 7498,
                'data_emissao' => '2007-06-18',
            'corpo_nf' => 'Parcela 2 de 2 referente a OS 001 de desenvolvimento e implantação do portal colaborativo da Assurant. UFI (Universo Finance & Insurance).
',
                'comissao_cn' => 14,
                'total_imp_inc' => 16,
            ),
            73 => 
            array (
                'co_fatura' => 76,
                'co_cliente' => 6991,
                'co_sistema' => 126,
                'co_os' => 1156,
                'num_nf' => 0,
                'total' => 350,
                'valor' => 350,
                'data_emissao' => '2007-06-25',
                'corpo_nf' => 'upgrade CMS.',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            74 => 
            array (
                'co_fatura' => 77,
                'co_cliente' => 7046,
                'co_sistema' => 263,
                'co_os' => 1147,
                'num_nf' => 528,
                'total' => 3650,
                'valor' => 3595.25,
                'data_emissao' => '2007-06-27',
                'corpo_nf' => 'Parcela 1 de 4 referente a OS 001 de transposição do fonte java do site atual Zion para o novo site desenvolvido pela Click',
                'comissao_cn' => 14,
                'total_imp_inc' => 21,
            ),
            75 => 
            array (
                'co_fatura' => 78,
                'co_cliente' => 7048,
                'co_sistema' => 270,
                'co_os' => 1157,
                'num_nf' => 0,
                'total' => 2640,
                'valor' => 2640,
                'data_emissao' => '2007-06-28',
                'corpo_nf' => 'Parcela 1/10 de Sistemas Web Doup.',
                'comissao_cn' => 13,
                'total_imp_inc' => 0,
            ),
            76 => 
            array (
                'co_fatura' => 79,
                'co_cliente' => 7049,
                'co_sistema' => 271,
                'co_os' => 1167,
                'num_nf' => 0,
                'total' => 802.3699951171875,
                'valor' => 802.3699951171875,
                'data_emissao' => '2007-06-28',
                'corpo_nf' => 'OS001 Plataforma Moodle -> Upgrade',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            77 => 
            array (
                'co_fatura' => 80,
                'co_cliente' => 7042,
                'co_sistema' => 272,
                'co_os' => 1169,
                'num_nf' => 0,
                'total' => 640,
                'valor' => 640,
                'data_emissao' => '2007-06-29',
                'corpo_nf' => 'desenvolvimento do website Tecnutri - parcela 1/5',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            78 => 
            array (
                'co_fatura' => 81,
                'co_cliente' => 6983,
                'co_sistema' => 205,
                'co_os' => 1170,
                'num_nf' => 0,
                'total' => 400,
                'valor' => 400,
                'data_emissao' => '2007-06-29',
                'corpo_nf' => 'implementações do website Fitoguard',
                'comissao_cn' => 5,
                'total_imp_inc' => 0,
            ),
            79 => 
            array (
                'co_fatura' => 82,
                'co_cliente' => 7040,
                'co_sistema' => 252,
                'co_os' => 1079,
                'num_nf' => 529,
                'total' => 2968.02001953125,
                'valor' => 2923.5,
                'data_emissao' => '2007-07-02',
                'corpo_nf' => 'Parcela 02 de 04. referente a OS 001 que contempla o desenvolvimento e a implantação do SPO - Sistema de Pedidos Online da Compactor.',
                'comissao_cn' => 14,
                'total_imp_inc' => 16,
            ),
            80 => 
            array (
                'co_fatura' => 83,
                'co_cliente' => 7038,
                'co_sistema' => 256,
                'co_os' => 1094,
                'num_nf' => 530,
                'total' => 2833.330078125,
                'valor' => 2790.830078125,
                'data_emissao' => '2007-07-02',
                'corpo_nf' => 'consultoria de processos. análise de sistemas e geração de documentos',
                'comissao_cn' => 15,
                'total_imp_inc' => 16,
            ),
            81 => 
            array (
                'co_fatura' => 84,
                'co_cliente' => 3,
                'co_sistema' => 152,
                'co_os' => 1135,
                'num_nf' => 531,
                'total' => 1258.8800048828125,
                'valor' => 1240,
                'data_emissao' => '2007-07-04',
                'corpo_nf' => 'Referente a 20 horas de desenvolvimento de upgrade no sistema Fleet Control de MANUTENÇÃO DE DADOS DE ENTRADA / SAÍDA.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            82 => 
            array (
                'co_fatura' => 85,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 532,
                'total' => 10278.099609375,
                'valor' => 9646,
                'data_emissao' => '2007-07-04',
                'corpo_nf' => 'Referente a 182 horas do mês de junho de 2007 de alocação do recurso Francisco Ogatha em análise/desenvolvimento de sistemas java.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            83 => 
            array (
                'co_fatura' => 86,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 859,
                'num_nf' => 533,
                'total' => 9035.7001953125,
                'valor' => 8480,
                'data_emissao' => '2007-07-04',
                'corpo_nf' => 'Referente a 160 horas do mês de junho de 2007 de alocação de recurso java para o desenvolvimento de sistemas para a área de Vendas.
',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            84 => 
            array (
                'co_fatura' => 87,
                'co_cliente' => 4343,
                'co_sistema' => 200,
                'co_os' => 1174,
                'num_nf' => 534,
                'total' => 3045.68994140625,
                'valor' => 3000,
                'data_emissao' => '2007-07-05',
                'corpo_nf' => 'Parcela única referente ao desenvolvimento de nova área para sistema SGPF. OS 005 do sistema.',
                'comissao_cn' => 10,
                'total_imp_inc' => 21,
            ),
            85 => 
            array (
                'co_fatura' => 88,
                'co_cliente' => 7035,
                'co_sistema' => 249,
                'co_os' => 1049,
                'num_nf' => 535,
                'total' => 3476.139892578125,
                'valor' => 3424,
                'data_emissao' => '2007-07-06',
                'corpo_nf' => 'Parcela 02 de 02. referente a OS 001 que contempla o desenvolvimento e a implantação do sistema SPO - Sistema de Pedidos OnLine.
',
                'comissao_cn' => 15,
                'total_imp_inc' => 16,
            ),
            86 => 
            array (
                'co_fatura' => 89,
                'co_cliente' => 7043,
                'co_sistema' => 258,
                'co_os' => 1177,
                'num_nf' => 536,
                'total' => 2199.659912109375,
                'valor' => 2166.669921875,
                'data_emissao' => '2007-07-09',
            'corpo_nf' => 'Parcela 1 de 12 referente a OS 002 de hospedagem. manutenção preventiva. corretiva e evolutiva (500 hrs) do Portal UFI.',
                'comissao_cn' => 8,
                'total_imp_inc' => 16,
            ),
            87 => 
            array (
                'co_fatura' => 90,
                'co_cliente' => 6945,
                'co_sistema' => 173,
                'co_os' => 1004,
                'num_nf' => 537,
                'total' => 150,
                'valor' => 147.75,
                'data_emissao' => '2007-07-09',
                'corpo_nf' => 'adaptacao do menu',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            88 => 
            array (
                'co_fatura' => 92,
                'co_cliente' => 7040,
                'co_sistema' => 252,
                'co_os' => 1190,
                'num_nf' => 539,
                'total' => 2883.340087890625,
                'valor' => 2568,
                'data_emissao' => '2007-07-10',
                'corpo_nf' => 'Referente a OS 002 que contempla um upgrade no desenvolvimento e a implantação do SPO - Sistema de Pedidos Online da Compactor.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            89 => 
            array (
                'co_fatura' => 93,
                'co_cliente' => 7031,
                'co_sistema' => 247,
                'co_os' => 999,
                'num_nf' => 540,
                'total' => 6425,
                'valor' => 6029.85986328125,
                'data_emissao' => '2007-07-12',
                'corpo_nf' => 'Parcela 2 de 2 referente consultoria e desenvolvimento de adequações SisconDJ 2.0 para a Lei Federal 10.819/2003.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            90 => 
            array (
                'co_fatura' => 94,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 1194,
                'num_nf' => 541,
                'total' => 3090.0400390625,
                'valor' => 2900,
                'data_emissao' => '2007-07-12',
            'corpo_nf' => 'Parcela 1 de 12 referente a OS 001 de suporte. manutenção preventiva. corretiva e evolutiva dos sistemas Toyota (600 hrs). Sistemas sobre a gestão de Vanderlei Caetano.
',
                'comissao_cn' => 7,
                'total_imp_inc' => 16,
            ),
            91 => 
            array (
                'co_fatura' => 95,
                'co_cliente' => 46,
                'co_sistema' => 113,
                'co_os' => 1175,
                'num_nf' => 0,
                'total' => 3056,
                'valor' => 3056,
                'data_emissao' => '2007-07-12',
                'corpo_nf' => 'OS011 – Refactoring / Redesign do Website e Administração',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            92 => 
            array (
                'co_fatura' => 96,
                'co_cliente' => 2,
                'co_sistema' => 102,
                'co_os' => 1202,
                'num_nf' => 542,
                'total' => 2912,
                'valor' => 2868.320068359375,
                'data_emissao' => '2007-07-16',
                'corpo_nf' => 'Parcela 1 de 2 referente a OS 16 de desenvolvimento e implantação de upgrade na versão 2.0 do sisconDJ MT.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            93 => 
            array (
                'co_fatura' => 97,
                'co_cliente' => 2,
                'co_sistema' => 102,
                'co_os' => 1202,
                'num_nf' => 543,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-07-16',
                'corpo_nf' => 'Parcela referente a manutenção do mês de junho-julho/2007 das funcionalidades existentes no SisconDJ instalado no TJMT.
',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            94 => 
            array (
                'co_fatura' => 98,
                'co_cliente' => 7031,
                'co_sistema' => 149,
                'co_os' => 425,
                'num_nf' => 544,
                'total' => 1700,
                'valor' => 1296.68994140625,
                'data_emissao' => '2007-07-16',
                'corpo_nf' => 'Parcela referente a manutenção do mês de junho-julho/2007 das funcionalidades existentes no SisconDJ instalado no TJAM.',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            95 => 
            array (
                'co_fatura' => 99,
                'co_cliente' => 7046,
                'co_sistema' => 263,
                'co_os' => 1147,
                'num_nf' => 551,
                'total' => 3650,
                'valor' => 3595.25,
                'data_emissao' => '2007-07-17',
                'corpo_nf' => 'Parcela 2 de 4 referente a OS 001 de transposição do fonte java do site atual Zion para o novo site desenvolvido pela Click.',
                'comissao_cn' => 14,
                'total_imp_inc' => 21,
            ),
            96 => 
            array (
                'co_fatura' => 100,
                'co_cliente' => 7047,
                'co_sistema' => 264,
                'co_os' => 1150,
                'num_nf' => 552,
                'total' => 2880.72998046875,
                'valor' => 2837.52001953125,
                'data_emissao' => '2007-07-23',
            'corpo_nf' => 'Parcela 02 de 05. referente a OS 001 que contempla Refactoring e Redesign do Website Chevrolet Nova e dos cinco Hotsites de frotistas mantidos pelo grupo (Citiclub. CIMEB. Central do Hoteleiro. Novartis e Unilever).',
                'comissao_cn' => 14,
                'total_imp_inc' => 21,
            ),
            97 => 
            array (
                'co_fatura' => 101,
                'co_cliente' => 7050,
                'co_sistema' => 275,
                'co_os' => 1195,
                'num_nf' => 0,
                'total' => 630,
                'valor' => 630,
                'data_emissao' => '2007-07-25',
                'corpo_nf' => 'Banco de 150 horas para a empresa Sina Enxovais. Parcela 1/10',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            98 => 
            array (
                'co_fatura' => 102,
                'co_cliente' => 6949,
                'co_sistema' => 262,
                'co_os' => 1143,
                'num_nf' => 554,
                'total' => 58200,
                'valor' => 54620.69921875,
                'data_emissao' => '2007-07-30',
                'corpo_nf' => 'Desenvolvimento e implantação das seguintes tarefas/funcionalidades:

- Ferramenta PEX - sistema de automação (15.000.00)
- Manutenção corretiva (12 meses) (13.200.00)
- Manutenção evolutiva (500 horas) (30.000.00)

código do fornecedor: 3024729
Nº do pedido: 4500331026
data de emissão do pedido: 15/06/2007',
                'comissao_cn' => 5,
                'total_imp_inc' => 16,
            ),
            99 => 
            array (
                'co_fatura' => 103,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 555,
                'total' => 10069.2998046875,
                'valor' => 9450,
                'data_emissao' => '2007-08-01',
                'corpo_nf' => 'Referente a 180 horas do mês de julho de 2007 de alocação do recurso Francisco Ogatha em análise/desenvolvimento de sistemas java.
',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            100 => 
            array (
                'co_fatura' => 104,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 859,
                'num_nf' => 556,
                'total' => 9882.7900390625,
                'valor' => 9275,
                'data_emissao' => '2007-08-01',
                'corpo_nf' => 'Referente a 175 horas do mês de julho de 2007 de alocação de recurso java para o desenvolvimento de sistemas para a área de Vendas.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            101 => 
            array (
                'co_fatura' => 105,
                'co_cliente' => 7043,
                'co_sistema' => 258,
                'co_os' => 1177,
                'num_nf' => 557,
                'total' => 2199.659912109375,
                'valor' => 2166.669921875,
                'data_emissao' => '2007-08-06',
            'corpo_nf' => 'Parcela 2 de 12 referente a OS 002 de hospedagem. manutenção preventiva. corretiva e evolutiva (500 hrs) do Portal UFI.',
                'comissao_cn' => 8,
                'total_imp_inc' => 16,
            ),
            102 => 
            array (
                'co_fatura' => 106,
                'co_cliente' => 7039,
                'co_sistema' => 251,
                'co_os' => 1236,
                'num_nf' => 0,
                'total' => 336,
                'valor' => 336,
                'data_emissao' => '2007-08-06',
                'corpo_nf' => 'Publicação do Clipping Julho/07',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            103 => 
            array (
                'co_fatura' => 107,
                'co_cliente' => 7048,
                'co_sistema' => 270,
                'co_os' => 1157,
                'num_nf' => 0,
                'total' => 2640,
                'valor' => 2640,
                'data_emissao' => '2007-08-02',
                'corpo_nf' => 'Parcela 2/10 de Sistemas Web Doup',
                'comissao_cn' => 13,
                'total_imp_inc' => 0,
            ),
            104 => 
            array (
                'co_fatura' => 108,
                'co_cliente' => 7040,
                'co_sistema' => 252,
                'co_os' => 1079,
                'num_nf' => 558,
                'total' => 2968.02001953125,
                'valor' => 2923.5,
                'data_emissao' => '2007-08-07',
                'corpo_nf' => 'Parcela 03 de 04. referente a OS 001 que contempla o desenvolvimento e a implantação do SPO - Sistema de Pedidos Online da Compactor.',
                'comissao_cn' => 14,
                'total_imp_inc' => 16,
            ),
            105 => 
            array (
                'co_fatura' => 109,
                'co_cliente' => 7035,
                'co_sistema' => 273,
                'co_os' => 1173,
                'num_nf' => 560,
                'total' => 7160.35986328125,
                'valor' => 6720,
                'data_emissao' => '2007-08-07',
                'corpo_nf' => 'Referente a OS 002 que contempla o desenvolvimento e a implantação de sistemas.',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            106 => 
            array (
                'co_fatura' => 110,
                'co_cliente' => 46,
                'co_sistema' => 113,
                'co_os' => 1175,
                'num_nf' => 0,
                'total' => 3056,
                'valor' => 3056,
                'data_emissao' => '2007-08-13',
                'corpo_nf' => 'OS011 – Refactoring / Redesign do Website e Administração - parcela 2/3',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            107 => 
            array (
                'co_fatura' => 111,
                'co_cliente' => 2,
                'co_sistema' => 102,
                'co_os' => 1202,
                'num_nf' => 567,
                'total' => 2912,
                'valor' => 2868.320068359375,
                'data_emissao' => '2007-08-16',
                'corpo_nf' => 'Parcela 2 de 2 referente a OS 16 de desenvolvimento e implantação de upgrade na versão 2.0 do sisconDJ MT',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            108 => 
            array (
                'co_fatura' => 112,
                'co_cliente' => 2,
                'co_sistema' => 102,
                'co_os' => 1202,
                'num_nf' => 568,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-08-16',
                'corpo_nf' => 'Parcela referente a manutenção do mês de julho-agosto/2007 das funcionalidades existentes no SisconDJ instalado no TJMT',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            109 => 
            array (
                'co_fatura' => 113,
                'co_cliente' => 7031,
                'co_sistema' => 149,
                'co_os' => 425,
                'num_nf' => 569,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-08-16',
                'corpo_nf' => 'Parcela referente a manutenção do mês de julho-agosto/2007 das funcionalidades existentes no SisconDJ instalado no TJAM.',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            110 => 
            array (
                'co_fatura' => 114,
                'co_cliente' => 7046,
                'co_sistema' => 263,
                'co_os' => 1147,
                'num_nf' => 570,
                'total' => 3650,
                'valor' => 3595.25,
                'data_emissao' => '2007-08-16',
                'corpo_nf' => 'Parcela 3 de 4 referente a OS 001 de transposição do fonte java do site atual Zion para o novo site desenvolvido pela Click.',
                'comissao_cn' => 14,
                'total_imp_inc' => 21,
            ),
            111 => 
            array (
                'co_fatura' => 115,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 1194,
                'num_nf' => 571,
                'total' => 3090.0400390625,
                'valor' => 2900,
                'data_emissao' => '2007-08-16',
            'corpo_nf' => 'Parcela 2 de 12 referente a OS 001 de suporte. manutenção preventiva. corretiva e evolutiva dos sistemas Toyota (600 hrs). Sistemas sobre a gestão de Vanderlei Caetano.
',
                'comissao_cn' => 7,
                'total_imp_inc' => 16,
            ),
            112 => 
            array (
                'co_fatura' => 116,
                'co_cliente' => 7055,
                'co_sistema' => 281,
                'co_os' => 1243,
                'num_nf' => 0,
                'total' => 1380,
                'valor' => 1380,
                'data_emissao' => '2007-08-20',
                'corpo_nf' => 'Qualitec Consultoria Imobiliária Ltda. – Projeto – Redesing do Web Site www.qualitecimoveis.com.br. parcela 1/4',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            113 => 
            array (
                'co_fatura' => 117,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 572,
                'total' => 2097.64990234375,
                'valor' => 2066.18994140625,
                'data_emissao' => '2007-08-20',
                'corpo_nf' => 'Parcela 1 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
            114 => 
            array (
                'co_fatura' => 118,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 573,
                'total' => 524.41998291015625,
                'valor' => 516.54998779296875,
                'data_emissao' => '2007-08-20',
                'corpo_nf' => 'Parcela 1 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.
',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
            115 => 
            array (
                'co_fatura' => 119,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 574,
                'total' => 524.41998291015625,
                'valor' => 516.54998779296875,
                'data_emissao' => '2007-08-20',
                'corpo_nf' => 'Parcela 1 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
            116 => 
            array (
                'co_fatura' => 120,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 575,
                'total' => 524.41998291015625,
                'valor' => 516.54998779296875,
                'data_emissao' => '2007-08-20',
                'corpo_nf' => 'Parcela 1 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.
',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
            117 => 
            array (
                'co_fatura' => 121,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 576,
                'total' => 1573.25,
                'valor' => 1305.800048828125,
                'data_emissao' => '2007-08-20',
                'corpo_nf' => 'Parcela 1 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
            118 => 
            array (
                'co_fatura' => 122,
                'co_cliente' => 7048,
                'co_sistema' => 270,
                'co_os' => 1157,
                'num_nf' => 0,
                'total' => 2640,
                'valor' => 2640,
                'data_emissao' => '2007-08-23',
                'corpo_nf' => 'Parcela 3/10 de Sistemas Web Doup.',
                'comissao_cn' => 13,
                'total_imp_inc' => 0,
            ),
            119 => 
            array (
                'co_fatura' => 123,
                'co_cliente' => 7050,
                'co_sistema' => 275,
                'co_os' => 1195,
                'num_nf' => 0,
                'total' => 630,
                'valor' => 630,
                'data_emissao' => '2007-08-27',
                'corpo_nf' => 'Banco de 150 horas para a empresa Sina Enxovais. Parcela 2/10',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            120 => 
            array (
                'co_fatura' => 124,
                'co_cliente' => 7052,
                'co_sistema' => 278,
                'co_os' => 1234,
                'num_nf' => 0,
                'total' => 936.65997314453125,
                'valor' => 936.65997314453125,
                'data_emissao' => '2007-08-03',
                'corpo_nf' => 'parcela 1/6 projeto website',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            121 => 
            array (
                'co_fatura' => 125,
                'co_cliente' => 7049,
                'co_sistema' => 271,
                'co_os' => 1260,
                'num_nf' => 0,
                'total' => 595.20001220703125,
                'valor' => 595.20001220703125,
                'data_emissao' => '2007-08-29',
                'corpo_nf' => 'Em 3 pagamentos iguais de R$ 595.20 sendo o primeiro a vista em 30 e 60 dias após o primeiro pagamento.',
                'comissao_cn' => 10,
                'total_imp_inc' => 0,
            ),
            122 => 
            array (
                'co_fatura' => 126,
                'co_cliente' => 7047,
                'co_sistema' => 264,
                'co_os' => 1150,
                'num_nf' => 579,
                'total' => 2880.72998046875,
                'valor' => 2837.52001953125,
                'data_emissao' => '2007-08-31',
            'corpo_nf' => 'Parcela 03 de 05. referente a OS 001 que contempla Refactoring e Redesign do Website Chevrolet Nova e dos cinco Hotsites de frotistas mantidos pelo grupo (Citiclub. CIMEB. Central do Hoteleiro. Novartis e Unilever).
',
                'comissao_cn' => 14,
                'total_imp_inc' => 21,
            ),
            123 => 
            array (
                'co_fatura' => 128,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 291,
                'num_nf' => 581,
                'total' => 10955.7998046875,
                'valor' => 10282,
                'data_emissao' => '2007-09-03',
                'corpo_nf' => 'Referente a 194 horas do mês de agosto/2007 de alocação do recurso Francisco Ogatha em análise/desenvolvimento de sistemas java.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            124 => 
            array (
                'co_fatura' => 129,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 859,
                'num_nf' => 582,
                'total' => 10391,
                'valor' => 9752,
                'data_emissao' => '2007-09-03',
                'corpo_nf' => 'Referente a 184 horas do mês de agosto de 2007 de alocação de recurso java para o desenvolvimento de sistemas para a área de Vendas.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            125 => 
            array (
                'co_fatura' => 133,
                'co_cliente' => 6796,
                'co_sistema' => 282,
                'co_os' => 1247,
                'num_nf' => 585,
                'total' => 9589.76953125,
                'valor' => 9000,
                'data_emissao' => '2007-09-03',
                'corpo_nf' => 'Parcela 1 de 4 referente a OS 001 de Desenvolvimento e implantação do Sistema de Acompanhamento On-Line.',
                'comissao_cn' => 12,
                'total_imp_inc' => 21,
            ),
            126 => 
            array (
                'co_fatura' => 137,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 1266,
                'num_nf' => 588,
                'total' => 6073.52001953125,
                'valor' => 5700,
                'data_emissao' => '2007-09-04',
                'corpo_nf' => 'Parcela 1 de 2 referente a OS 012 de Consultoria em pesquisa e análise dos ERPs utilizados pelas concessionárias Toyota.',
                'comissao_cn' => 9,
                'total_imp_inc' => 16,
            ),
            127 => 
            array (
                'co_fatura' => 138,
                'co_cliente' => 7028,
                'co_sistema' => 240,
                'co_os' => 1161,
                'num_nf' => 589,
                'total' => 2411.169921875,
                'valor' => 2375,
                'data_emissao' => '2007-09-04',
                'corpo_nf' => 'Referente a OS 002 que contempla manutenção do sitema web SAPP – Sistema de Acompanhamento de Projeto Pedagógico.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            128 => 
            array (
                'co_fatura' => 139,
                'co_cliente' => 6936,
                'co_sistema' => 250,
                'co_os' => 1050,
                'num_nf' => 590,
                'total' => 5320,
                'valor' => 4992.81982421875,
                'data_emissao' => '2007-09-04',
                'corpo_nf' => 'Desenvolvimento de sistema administrativo para o website da JICA – Agência de Cooperação Internacional do Japão.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            129 => 
            array (
                'co_fatura' => 140,
                'co_cliente' => 7053,
                'co_sistema' => 279,
                'co_os' => 1238,
                'num_nf' => 591,
                'total' => 6925.9501953125,
                'valor' => 6500,
                'data_emissao' => '2007-09-05',
                'corpo_nf' => 'Referente à 125 horas do mês de agosto/2007 de alocação do recurso André Tinchant em análise/desenvolvimento de sistemas na linguagem .Net C#.

',
                'comissao_cn' => 10,
                'total_imp_inc' => 27,
            ),
            130 => 
            array (
                'co_fatura' => 141,
                'co_cliente' => 7053,
                'co_sistema' => 279,
                'co_os' => 1238,
                'num_nf' => 592,
                'total' => 5370.27001953125,
                'valor' => 5040,
                'data_emissao' => '2007-09-05',
                'corpo_nf' => 'Referente à 120 horas do mês de agosto/2007 de alocação do recurso Rodrigo Caio Salim Valenzuela em diagramação. recorte e construção em HTML.',
                'comissao_cn' => 10,
                'total_imp_inc' => 27,
            ),
            131 => 
            array (
                'co_fatura' => 142,
                'co_cliente' => 7040,
                'co_sistema' => 252,
                'co_os' => 1079,
                'num_nf' => 593,
                'total' => 2968.02001953125,
                'valor' => 2923.5,
                'data_emissao' => '2007-09-05',
                'corpo_nf' => 'Parcela 04 de 04. referente a OS 001 que contempla o desenvolvimento e a implantação do SPO - Sistema de Pedidos Online da Compactor.',
                'comissao_cn' => 14,
                'total_imp_inc' => 16,
            ),
            132 => 
            array (
                'co_fatura' => 143,
                'co_cliente' => 7040,
                'co_sistema' => 252,
                'co_os' => 1079,
                'num_nf' => 594,
                'total' => 3192.330078125,
                'valor' => 2996,
                'data_emissao' => '2007-09-05',
                'corpo_nf' => 'Referente a OS 003 que contempla um upgrade no desenvolvimento e a implantação do SPO - Sistema de Pedidos Online da Compactor.',
                'comissao_cn' => 10,
                'total_imp_inc' => 16,
            ),
            133 => 
            array (
                'co_fatura' => 144,
                'co_cliente' => 7035,
                'co_sistema' => 257,
                'co_os' => 1098,
                'num_nf' => 595,
                'total' => 7160.35986328125,
                'valor' => 6720,
                'data_emissao' => '2007-09-05',
                'corpo_nf' => 'Referente ao mês de Agosto/07 da OS 002 que contempla o desenvolvimento e a implantação de sistemas.',
                'comissao_cn' => 10,
                'total_imp_inc' => 21,
            ),
            134 => 
            array (
                'co_fatura' => 145,
                'co_cliente' => 7052,
                'co_sistema' => 278,
                'co_os' => 1234,
                'num_nf' => 0,
                'total' => 936.65997314453125,
                'valor' => 936.65997314453125,
                'data_emissao' => '2007-09-05',
                'corpo_nf' => 'parcela 2/6 projeto website',
                'comissao_cn' => 15,
                'total_imp_inc' => 0,
            ),
            135 => 
            array (
                'co_fatura' => 146,
                'co_cliente' => 7043,
                'co_sistema' => 258,
                'co_os' => 1177,
                'num_nf' => 596,
                'total' => 2199.659912109375,
                'valor' => 2166.669921875,
                'data_emissao' => '2007-09-11',
            'corpo_nf' => 'Parcela 3 de 12 referente a OS 002 de hospedagem. manutenção preventiva. corretiva e evolutiva (500 hrs) do Portal UFI.',
                'comissao_cn' => 8,
                'total_imp_inc' => 16,
            ),
            136 => 
            array (
                'co_fatura' => 147,
                'co_cliente' => 3,
                'co_sistema' => 175,
                'co_os' => 1194,
                'num_nf' => 597,
                'total' => 3090.0400390625,
                'valor' => 2900,
                'data_emissao' => '2007-09-11',
            'corpo_nf' => 'Parcela 3 de 12 referente a OS 001 de suporte. manutenção preventiva. corretiva e evolutiva dos sistemas Toyota (600 hrs). Sistemas sobre a gestão de Vanderlei Caetano.',
                'comissao_cn' => 7,
                'total_imp_inc' => 16,
            ),
            137 => 
            array (
                'co_fatura' => 148,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 598,
                'total' => 6245.4599609375,
                'valor' => 5861.35986328125,
                'data_emissao' => '2007-09-12',
                'corpo_nf' => 'Elaboracao de programas software. Conforme OS-SF-001. OS-SF-002. OS-SF-005. OS-SF-028.',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            138 => 
            array (
                'co_fatura' => 149,
                'co_cliente' => 6947,
                'co_sistema' => 181,
                'co_os' => 394,
                'num_nf' => 603,
                'total' => 5085.990234375,
                'valor' => 4773.2001953125,
                'data_emissao' => '2007-09-12',
                'corpo_nf' => 'Elaboracao de programas software. Conforme OS-SF-001. OS-SF-002. OS-SF-005. OS-SF-028.',
                'comissao_cn' => 6,
                'total_imp_inc' => 21,
            ),
            139 => 
            array (
                'co_fatura' => 150,
                'co_cliente' => 7056,
                'co_sistema' => 284,
                'co_os' => 1269,
                'num_nf' => 0,
                'total' => 2539.77001953125,
                'valor' => 2539.77001953125,
                'data_emissao' => '2007-09-13',
                'corpo_nf' => 'pagamento da 1ª parcela de 5 do Website Perfin',
                'comissao_cn' => 14,
                'total_imp_inc' => 0,
            ),
            140 => 
            array (
                'co_fatura' => 151,
                'co_cliente' => 2,
                'co_sistema' => 102,
                'co_os' => 1202,
                'num_nf' => 604,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-09-14',
                'corpo_nf' => 'Parcela referente a manutenção do mês de agosto-setembro/2007 das funcionalidades existentes no SisconDJ instalado no TJMT',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            141 => 
            array (
                'co_fatura' => 152,
                'co_cliente' => 7031,
                'co_sistema' => 149,
                'co_os' => 425,
                'num_nf' => 605,
                'total' => 1700,
                'valor' => 1674.5,
                'data_emissao' => '2007-09-14',
                'corpo_nf' => 'Parcela referente a manutenção do mês de agosto-setembro/2007 das funcionalidades existentes no SisconDJ instalado no TJAM.',
                'comissao_cn' => 0,
                'total_imp_inc' => 16,
            ),
            142 => 
            array (
                'co_fatura' => 153,
                'co_cliente' => 3,
                'co_sistema' => 166,
                'co_os' => 1055,
                'num_nf' => 606,
                'total' => 7991.47998046875,
                'valor' => 7500,
                'data_emissao' => '2007-09-14',
                'corpo_nf' => 'Parcela 4 de 4 referente a OS 001 de desenvolvimento de upgrade no sistema. contemplando novas funcionalidades. novos relatórios e ajustes em relatórios existentes.',
                'comissao_cn' => 8,
                'total_imp_inc' => 16,
            ),
            143 => 
            array (
                'co_fatura' => 154,
                'co_cliente' => 7046,
                'co_sistema' => 263,
                'co_os' => 1147,
                'num_nf' => 607,
                'total' => 3650,
                'valor' => 3595.25,
                'data_emissao' => '2007-09-14',
                'corpo_nf' => 'Parcela 4 de 4 referente a OS 001 de transposição do fonte java do site atual Zion para o novo site desenvolvido pela Click.
',
                'comissao_cn' => 14,
                'total_imp_inc' => 21,
            ),
            144 => 
            array (
                'co_fatura' => 155,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 608,
                'total' => 2097.64990234375,
                'valor' => 2066.18994140625,
                'data_emissao' => '2007-09-17',
                'corpo_nf' => 'Parcela 2 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.',
                'comissao_cn' => 13,
                'total_imp_inc' => 21,
            ),
            145 => 
            array (
                'co_fatura' => 156,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 609,
                'total' => 524.41998291015625,
                'valor' => 516.54998779296875,
                'data_emissao' => '2007-09-17',
                'corpo_nf' => 'Parcela 2 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.',
                'comissao_cn' => 13,
                'total_imp_inc' => 21,
            ),
            146 => 
            array (
                'co_fatura' => 157,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 610,
                'total' => 524.41998291015625,
                'valor' => 516.54998779296875,
                'data_emissao' => '2007-09-17',
                'corpo_nf' => 'Parcela 2 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.',
                'comissao_cn' => 13,
                'total_imp_inc' => 21,
            ),
            147 => 
            array (
                'co_fatura' => 158,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 611,
                'total' => 524.41998291015625,
                'valor' => 516.54998779296875,
                'data_emissao' => '2007-09-17',
                'corpo_nf' => 'Parcela 2 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.',
                'comissao_cn' => 13,
                'total_imp_inc' => 21,
            ),
            148 => 
            array (
                'co_fatura' => 159,
                'co_cliente' => 7054,
                'co_sistema' => 280,
                'co_os' => 1242,
                'num_nf' => 612,
                'total' => 1573.25,
                'valor' => 1305.800048828125,
                'data_emissao' => '2007-09-17',
                'corpo_nf' => 'Parcela 2 de 5 referente a OS 001 de Desenvolvimento e implantação do portal da empresa.',
                'comissao_cn' => 13,
                'total_imp_inc' => 21,
            ),
            149 => 
            array (
                'co_fatura' => 160,
                'co_cliente' => 7048,
                'co_sistema' => 270,
                'co_os' => 1157,
                'num_nf' => 0,
                'total' => 2640,
                'valor' => 2640,
                'data_emissao' => '2007-09-17',
                'corpo_nf' => 'Parcela 4/10 de Sistemas Web Doup.',
                'comissao_cn' => 13,
                'total_imp_inc' => 0,
            ),
            150 => 
            array (
                'co_fatura' => 161,
                'co_cliente' => 3,
                'co_sistema' => 283,
                'co_os' => 1265,
                'num_nf' => 613,
                'total' => 9990,
                'valor' => 9375.6201171875,
                'data_emissao' => '2007-09-18',
                'corpo_nf' => 'Parcela 1 de 6 referente a OS 001 de Desenvolvimento e implantação do Portal Toyota VD.',
                'comissao_cn' => 5,
                'total_imp_inc' => 16,
            ),
            151 => 
            array (
                'co_fatura' => 162,
                'co_cliente' => 7058,
                'co_sistema' => 289,
                'co_os' => 1278,
                'num_nf' => 614,
                'total' => 536,
                'valor' => 527.96002197265625,
                'data_emissao' => '2007-09-18',
                'corpo_nf' => 'Parcela 01 de 02. referente a OS 001 que contempla ajustes no site da Antares Capital.',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
            152 => 
            array (
                'co_fatura' => 163,
                'co_cliente' => 7057,
                'co_sistema' => 286,
                'co_os' => 1272,
                'num_nf' => 615,
                'total' => 3426.39990234375,
                'valor' => 3375,
                'data_emissao' => '2007-09-18',
                'corpo_nf' => 'Parcela 01 de 02. referente ao Setup da OS 001 que contempla o desenvolvimento da Intranet do Grupo Brabus.',
                'comissao_cn' => 15,
                'total_imp_inc' => 21,
            ),
        ));
        
        
    }
}
